### ISSUE TITLE
Invalid tag names in tag / untag command should be ignored

### ISSUE THREAD

**Issue by jiaxinnns** [AY2425S1-CS2103T-W11-2/tp#173]
Currently, when the user enters an invalid tag name (eg. exceeds 50 characters), the error message is: The input length cannot exceed 50 characters.

If the tag is invalid, it definitely hasn't been created by the newtag command before (since newtag would also throw an error). 

So I feel that it can simply direct the user to the newtag command with:
Tag must be created first using (newtag) command.

**Comment by kvernnn** [comment]
I agree with what you said. In that case, it should throw a the MESSAGE_TAG_NOT_CREATED = "Tag(s) must be created first using 'newtag' command: " message in TagCommand class. However, I feel like we should not import this message into the TagCommandParser class, nor should we parse the argument > 50 characters into the TagCommand class for it to be handled then.

I feel like it should not tell the user to create it with the newtag command since if they attempt to do so it will throw the error.
Thus, I thought it would be appropriate to explicitly let the users know that the tag exceeds 50 characters. 

Let me know what you think or if there is a better message to give.
